### POST request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Ering Haaland",
  "email": "haaland9@example.com",
  "address": "99 Norway",
  "dateOfBirth": "2004-01-01",
  "registerDate": "2023-12-31"
}

###