### POST request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Dene Henderson",
  "email": "dene@example.com",
  "address": "222 BKK, Thailand",
  "dateOfBirth": "1995-04-07",
  "registerDate": "2019-04-07"
}

###